services:
  - type: web
    name: intellidocs-backend
    env: docker
    plan: free
    region: oregon
    buildCommand: docker build -t intellidocs-backend .
    startCommand: uvicorn main.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
      - key: GROQ_API_KEY
        sync: false
